### PR TITLE
refactor: large code file submission start

### PR DESCRIPTION
**Pull request by Cecilia-Nguyen**

### CODE REVIEW

**Comment by jakerenzella** [comment]
@macite Is this something you're involved in?

**Comment by macite** [comment]
Yes - this should be a draft PR to mark the start of the work... though I thought they had added a unit test that replicates the issue....

**Comment by macite** [comment]
@Cecilia-Nguyen can you make this a draft PR

**Comment by macite** [comment]
Wrong project - this should be in the submodule.

**Pull request closed without merging**
