### PR TITLE
Extra information for clarification

### PR DESCRIPTION
**Pull request by JAYson-deakin**
Change in Contributing.MD
Doc (text): Include other bash terminals that can be used for windows in getting started section 3 instruction

### CODE REVIEW

**Review by macite — CHANGES_REQUESTED** [review]
This looks good @JAYson-deakin. I just need you to update the commit message to use the format indicated in the contributing.md file 😄 

Please update this ASAP and then I can merge this.

**Comment by JAYson-deakin** [comment]
> This looks good @JAYson-deakin. I just need you to update the commit message to use the format indicated in the contributing.md file 😄
> 
> Please update this ASAP and then I can merge this.

How do you want it to format as I do not know in what format it needs to be in nor can I find it?

**Comment by JAYson-deakin** [comment]
> This looks good @JAYson-deakin. I just need you to update the commit message to use the format indicated in the contributing.md file 😄
> 
> Please update this ASAP and then I can merge this.

I have updated the commit message and i hope this is the right one

**Comment by macite** [comment]
Hi @JAYson-deakin, have a look at [Contributing.md](https://github.com/doubtfire-lms/doubtfire-deploy/blob/6.0.x/CONTRIBUTING.md#commit-message-format) at the commit message format.

You want this commit message to be something like "docs: include gitbash in windows instructions for cli"

**Comment by JAYson-deakin** [comment]
Hello @macite I have updated it again, and hopefully this is close to what i need to achieve

**Pull request closed without merging**
